language: python

sudo: false

python:
  - '3.5'
  - '2.7'
  - '2.5'
  - '2.6'
  - '3.4'
  - '3.0'
  - '3.1'
  - '3.2'
  - '3.3'

install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- python ./setup.py develop && COMPILE='--compile' make check
