version: 2
filters:
  branches:
    only: master
jobs:
  build-and-test:
    parallelism: 1
    shell: /bin/bash --login
    working_directory: ~/rocky/python-xdis
    docker:
    - image: circleci/python:3.7.11
    steps:
      - checkout
      - run:
        working_directory: ~/rocky/python-xdis
        command: sudo pip install nose
      - run:
          command: |
          sudo pip install -e .
          sudo pip install -r requirements-dev.txt

      - run: sudo python ./setup.py develop && make check-full
        name: Run Tests

workflows:
  main:
    jobs:
      - build-and-test
